apiVersion: v1
kind: Pod 
metadata:
  name: kubia-probe
  labels:
    app: kubia-probe
spec:
    containers:
    - name: kubia-probe-container
      image: registry.cn-shanghai.aliyuncs.com/sunchanghong/kubia:1.4
      livenessProbe:
        httpGet:
          path: /
          port: 8080
      ports:
        - containerPort: 8080

