apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia03
  namespace: xinyun-cicd
spec:
  replicas: 6
  selector:
    matchLabels:
      app: kubia03
  template:
    metadata:
      labels:
        app: kubia03
    spec:
      containers:
      - name: kubia03-container
        image: registry.cn-shanghai.aliyuncs.com/sunchanghong/kubia:1.2 
        ports:
        - containerPort: 8088

